import {
  ProjectTechStackType,
  ProjectStatus,
  TechStack,
  Employer,
} from "@/enums";
import { Project } from "../types";
import allezThumb from "@/assets/allez.png";
import dhThumbThumb from "@/assets/dh.png";
import dropshopThumb from "@/assets/dropshop.png";
import halkhataThumb from "@/assets/halkhata.png";
import ideezaThumb from "@/assets/ideeza.png";
import moresailingThumb from "@/assets/moresailing.png";
import roarThumb from "@/assets/roar.png";
import sessionzThumb from "@/assets/sessionz.png";
import shasthoThumb from "@/assets/shastho-ai.png";
import vaccinaThumb from "@/assets/vaccina.png";
import xThumb from "@/assets/x.webp";
import yumbaThumb from "@/assets/yumba.png";

export const projects: Project[] = [
  {
    name: "Dorpshop",
    status: ProjectStatus.ONLINE,
    employer: Employer.CROWDLINKER,
    techStackType: ProjectTechStackType.FRONTEND,
    description:
      "Dropshop is a Multi-tenant NFT e-commerce store powered by blockchain and crypto payment",
    thumbnail: dropshopThumb,
    url: "https://dropshop.io",
    gallery: ["dropshop-1.png"],
    tags: [
      "NFT",
      "E-commerce",
      "Blockchain",
      "Crypto Payment",
      "Multi-tenant",
      "Opensea",
    ],
    techStack: [
      TechStack.REACT,
      TechStack.NEXT,
      TechStack.TAILWIND,
      TechStack.GITHUB_ACTIONS,
      TechStack.AUTH0,
      TechStack.NODE,
      TechStack.NEST,
      TechStack.POSTGRESQL,
      TechStack.CSS,
      TechStack.JAVASCRIPT,
      TechStack.HTML,
      TechStack.TYPESCRIPT,
      TechStack.STRIPE,
      TechStack.DOCKER,
      TechStack.ESLINT,
      TechStack.PRETTIER,
    ],
  },
  {
    name: "Sessionz",
    techStackType: ProjectTechStackType.MOBILE,
    employer: Employer.CROWDLINKER,
    status: ProjectStatus.ONLINE,
    description:
      "Based in the vibrant city of Toronto, Canada, Sessionz is an innovative educational technology platform driven by a powerful vision: to make education accessible to all, regardless of background or location.",
    thumbnail: sessionzThumb,
    url: "https://sessionz.com",
    gallery: ["sessionz-1.png"],
    tags: [
      "Educational Technology",
      "E-learning",
      "Online Learning",
      "Tutoring",
      "Mentorship",
      "Edtech",
    ],
    techStack: [
      TechStack.REACT_NATIVE,
      TechStack.CSS,
      TechStack.JAVASCRIPT,
      TechStack.HTML,
      TechStack.TYPESCRIPT,
      TechStack.STRIPE,
      TechStack.XCODE,
      TechStack.FASTLANE,
      TechStack.ESLINT,
      TechStack.PRETTIER,
    ],
  },
  {
    name: "Yumba",
    status: ProjectStatus.ONLINE,
    employer: Employer.CROWDLINKER,
    techStackType: ProjectTechStackType.FULLSTACK,
    description: "Yumba is a Chef Cooked Meals Delivered Fresh To Your Door",
    thumbnail: yumbaThumb,
    url: "https://www.yumba.ca/",
    gallery: ["yumba-1.png"],
    tags: [
      "Food Delivery",
      "Meal Delivery",
      "Chef Cooked Meals",
      "Healthy Food",
      "Fresh Food",
      "B2C",
      "B2B",
      "Migration",
      "Subscription",
    ],
    techStack: [
      TechStack.REACT,
      TechStack.TAILWIND,
      TechStack.NODE,
      TechStack.POSTGRESQL,
      TechStack.MYSQL,
      TechStack.GITHUB_ACTIONS,
      TechStack.JAVASCRIPT,
      TechStack.TYPESCRIPT,
      TechStack.STRIPE,
      TechStack.DOCKER,
      TechStack.NEXT,
      TechStack.CSS,
      TechStack.HTML,
      TechStack.REACT_QUERY,
      TechStack.ZUSTAND,
      TechStack.JEST,
      TechStack.REST_API,
      TechStack.JWT,
      TechStack.ESLINT,
      TechStack.PRETTIER,
    ],
  },
  {
    name: "X",
    techStackType: ProjectTechStackType.FRONTEND,
    status: ProjectStatus.IN_DEVELOPMENT,
    employer: Employer.CROWDLINKER,
    description:
      "Project X (Confidential) is a next gen platform that connects people by AI audio match making. It's a social platform that allows music artists to connect with each other to collaborate and create music.",
    thumbnail: xThumb,
    url: null,
    gallery: ["x-1.png"],
    tags: [
      "AI",
      "Audio Match Making",
      "Social Platform",
      "Music Collaboration",
      "Music Artists",
      "AI Audio Processing",
    ],
    techStack: [
      TechStack.REACT,
      TechStack.TAILWIND,
      TechStack.JAVASCRIPT,
      TechStack.TYPESCRIPT,
      TechStack.GITHUB_ACTIONS,
      TechStack.DOCKER,
      TechStack.NEXT,
      TechStack.CSS,
      TechStack.HTML,
      TechStack.REACT_QUERY,
      TechStack.ZUSTAND,
      TechStack.REACT_TESTING_LIBRARY,
      TechStack.JEST,
      TechStack.REST_API,
      TechStack.JWT,
      TechStack.ESLINT,
      TechStack.PRETTIER,
    ],
  },
  {
    name: "Moresailing",
    techStackType: ProjectTechStackType.FRONTEND,
    status: ProjectStatus.ONLINE,
    employer: Employer.STRATIV_AB,
    description:
      "Moresailing is a booking platform for sailing trips and boats and a complete management solution. With More Sailing you can sail in Croatia, Greece, Italy, the Caribbean, Sweden or the Seychelles whether you are a beginner or an experienced sailor.",
    thumbnail: moresailingThumb,
    url: "https://www.moresailing.se/",
    gallery: ["moresailing-1.png"],
    tags: [
      "Booking Platform",
      "Sailing Trips",
      "Boats",
      "Management Solution",
      "B2C",
      "Multi vendor",
      "SaaS",
      "Klarna",
    ],
    techStack: [
      TechStack.REACT,
      TechStack.JAVASCRIPT,
      TechStack.DOCKER,
      TechStack.REDUX,
      TechStack.REDUX_SAGA,
      TechStack.STYLED_COMPONENTS,
      TechStack.CSS,
      TechStack.HTML,
      TechStack.HTML,
      TechStack.ANT_DESIGN,
      TechStack.REST_API,
      TechStack.JWT,
      TechStack.DIGITAL_OCEAN,
      TechStack.ESLINT,
      TechStack.PRETTIER,
    ],
  },
  {
    name: "Vaccina",
    techStackType: ProjectTechStackType.FRONTEND,
    status: ProjectStatus.ONLINE,
    employer: Employer.STRATIV_AB,
    description:
      "Vaccina is a robust platform and the go-to choice for purchasing vaccines.",
    thumbnail: vaccinaThumb,
    url: "https://www.kry.se/vaccina/",
    gallery: ["vaccina-1.png"],
    tags: [
      "Vaccine",
      "Healthcare",
      "E-commerce",
      "Pharmacy",
      "B2C",
      "B2B",
      "Klarna",
    ],
    techStack: [
      TechStack.REACT,
      TechStack.JAVASCRIPT,
      TechStack.REDUX,
      TechStack.REDUX_SAGA,
      TechStack.STYLED_COMPONENTS,
      TechStack.CSS,
      TechStack.HTML,
      TechStack.HTML,
      TechStack.REST_API,
      TechStack.JWT,
      TechStack.ESLINT,
      TechStack.PRETTIER,
    ],
  },
  {
    name: "Allez Padel",
    status: ProjectStatus.ONLINE,
    employer: Employer.STRATIV_AB,
    techStackType: ProjectTechStackType.FULLSTACK,
    description:
      "In this app, we have developed a fair, efficient but above all ranking system for Padel that suits EVERYONE",
    thumbnail: allezThumb,
    url: "https://appadvice.com/app/allez-padel/1608368550",
    gallery: ["allez-1.png"],
    tags: [
      "Padel",
      "Ranking System",
      "Sports",
      "Tournament",
      "Match",
      "Player",
      "Club",
      "League",
      "Social Network",
      "ELO",
    ],
    techStack: [
      TechStack.JAVASCRIPT,
      TechStack.TYPESCRIPT,
      TechStack.NEST,
      TechStack.MONGODB,
      TechStack.DOCKER,
      TechStack.PM2,
      TechStack.GITHUB_ACTIONS,
      TechStack.GITHUB_ACTIONS,
      TechStack.REACT_NATIVE,
      TechStack.SOCKET_IO,
      TechStack.REACT_QUERY,
      TechStack.REDUX,
      TechStack.JEST,
      TechStack.REDIS,
      TechStack.AWS,
      TechStack.ANDROID_STUDIO,
      TechStack.XCODE,
      TechStack.ESLINT,
      TechStack.PRETTIER,
    ],
  },
  {
    name: "Shastho AI",
    techStackType: ProjectTechStackType.FRONTEND,
    status: ProjectStatus.IN_DEVELOPMENT,
    employer: Employer.STRATIV_AB,
    description:
      "The one stop solution for managing healthcare in the most convenient way. It’s simple and easy- to provide healthcare in the fastest way possible.",
    thumbnail: shasthoThumb,
    url: "https://shastho.ai/",
    gallery: ["shastho-1.png"],
    tags: [
      "Healthcare",
      "Telemedicine",
      "E-commerce",
      "Pharmacy",
      "Payment Gateway",
      "Booking Platform",
      "Appointment Scheduling",
      "Digital Prescription",
      "Patient Management",
      "Patient History",
    ],
    techStack: [
      TechStack.REACT,
      TechStack.REACT_NATIVE,
      TechStack.JAVASCRIPT,
      TechStack.REDUX,
      TechStack.REDUX_SAGA,
      TechStack.STYLED_COMPONENTS,
      TechStack.CSS,
      TechStack.HTML,
      TechStack.HTML,
      TechStack.REST_API,
      TechStack.JWT,
      TechStack.ANDROID_STUDIO,
      TechStack.ESLINT,
      TechStack.PRETTIER,
    ],
  },
  {
    name: "Halkhata",
    techStackType: ProjectTechStackType.FULLSTACK,
    status: ProjectStatus.OFFLINE,
    employer: Employer.HALKHATA,
    description:
      "Digitize your business using the Halkhata app and manage all your transacitons simply and effortlessly. Gone are the days of doing business using pen and paper. The Halkhata app is the new way of doing business credit lending replacing the age-old manual process of recording on register khata.",
    thumbnail: halkhataThumb,
    url: "https://www.9apps.com/android-apps/com-halkhata/",
    gallery: ["halkhata-1.png"],
    tags: [
      "Business",
      "Credit Lending",
      "Digital Transaction",
      "Accounting",
      "Customer Management",
      "Payment Gateway",
      "E-commerce",
      "B2C",
      "Fintech",
      "Digital Payment",
      "Calender Management",
      "Reminder",
      "Digital Bookkeeping",
    ],
    techStack: [
      TechStack.JAVASCRIPT,
      TechStack.REACT_NATIVE,
      TechStack.REACT,
      TechStack.NODE,
      TechStack.JWT,
      TechStack.MONGODB,
      TechStack.PM2,
      TechStack.POSTMAN,
      TechStack.DIGITAL_OCEAN,
      TechStack.REDUX,
      TechStack.REDUX_SAGA,
      TechStack.STYLED_COMPONENTS,
      TechStack.CSS,
      TechStack.HTML,
      TechStack.REST_API,
      TechStack.ANDROID_STUDIO,
      TechStack.ESLINT,
      TechStack.PRETTIER,
    ],
  },
  {
    name: "Roar Media",
    techStackType: ProjectTechStackType.FRONTEND,
    status: ProjectStatus.ONLINE,
    employer: Employer.ROAR_GLOBAL,
    description:
      "Roar Media helps global organizations reach new audiences through content that inspires change across Asia.",
    thumbnail: roarThumb,
    url: "https://roar.media/english/",
    gallery: ["roar-1.png"],
    tags: [
      "Media",
      "Content",
      "News",
      "Journalism",
      "Asia",
      "Global",
      "Articles",
    ],
    techStack: [
      TechStack.JAVASCRIPT,
      TechStack.REACT_NATIVE,
      TechStack.REACT,
      TechStack.JWT,
      TechStack.REDUX,
      TechStack.REDUX_SAGA,
      TechStack.STYLED_COMPONENTS,
      TechStack.CSS,
      TechStack.SASS,
      TechStack.HTML,
      TechStack.REST_API,
      TechStack.ANDROID_STUDIO,
      TechStack.XCODE,
      TechStack.ESLINT,
      TechStack.PRETTIER,
    ],
  },
  {
    name: "Ideeza",
    techStackType: ProjectTechStackType.FRONTEND,
    status: ProjectStatus.IN_DEVELOPMENT,
    employer: Employer.ROAR_GLOBAL,
    description:
      "Meet IDEEZA, the only generative AI tool for Hardware product engineering that turns text into a blueprint in seconds.",
    thumbnail: ideezaThumb,
    url: "https://ideeza.com/",
    gallery: ["ideeza-1.png"],
    tags: [
      "Media",
      "Content",
      "News",
      "Journalism",
      "Asia",
      "Global",
      "Articles",
    ],
    techStack: [
      TechStack.JAVASCRIPT,
      TechStack.VUE,
      TechStack.JWT,
      TechStack.CSS,
      TechStack.SASS,
      TechStack.HTML,
      TechStack.REST_API,
      TechStack.POSTMAN,
      TechStack.ESLINT,
      TechStack.PRETTIER,
      TechStack.BABEL,
    ],
  },
  {
    name: "DeliveryHobe!",
    techStackType: ProjectTechStackType.FRONTEND,
    status: ProjectStatus.ONLINE,
    employer: Employer.ROAR_GLOBAL,
    description:
      "We power our local stores & their consumers through technology & memes.",
    thumbnail: dhThumbThumb,
    url: "https://www.deliveryhobe.com/",
    gallery: ["dh-1.png"],
    tags: [
      "Local Stores",
      "E-commerce",
      "Delivery",
      "Food",
      "Grocery",
      "Pharmacy",
      "B2C",
      "Delivery Management",
    ],
    techStack: [
      TechStack.JAVASCRIPT,
      TechStack.CSS,
      TechStack.HTML,
      TechStack.JQUERY,
      TechStack.REST_API,
    ],
  },
];
