export enum TechStackType {
  FRONTEND,
  BACKEND,
  TOOLS,
}

export const ModeTheme = {
  LIGHT: "light",
  DARK: "dark",
} as const;

export enum ProjectStatus {
  ONLINE = "online",
  IN_DEVELOPMENT = "in-development",
  OFFLINE = "offline",
}

export enum ProjectTechStackType {
  FRONTEND = "frontend",
  BACKEND = "backend",
  FULLSTACK = "fullstack",
  MOBILE = "mobile",
}

export enum Employer {
  SHIMAHIN = "shimahin",
  SHASTHO = "shastho",
  HALKHATA = "halkhata",
  ROAR_GLOBAL = "roar-global",
  STRATIV_AB = "strativ-ab",
  SHASTHO_AI = "shastho-ai",
  CROWDLINKER = "crowdlinker",
  NOTIONHIVE = "notionhive",
  IDEEZA = "ideeza",
}

export enum TechStack {
  REACT = "react",
  NEXT = "next",
  TAILWIND = "tailwind",
  NODE = "node",
  POSTGRESQL = "postgresql",
  CSS = "css",
  JAVASCRIPT = "javascript",
  HTML = "html",
  TYPESCRIPT = "typescript",
  REACT_NATIVE = "react-native",
  NEST = "nest",
  MONGODB = "mongodb",
  EXPRESS = "express",
  REDUX = "redux",
  REDUX_SAGA = "redux-saga",
  JEST = "jest",
  REACT_TESTING_LIBRARY = "react-testing-library",
  DIGITAL_OCEAN = "digital-ocean",
  AWS = "aws",
  SASS = "sass",
  ZUSTAND = "zustand",
  STRIPE = "stripe",
  JQUERY = "jquery",
  BOOTSTRAP = "bootstrap",
  REST_API = "rest-api",
  NGINX = "nginx",
  DOCKER = "docker",
  GIT = "git",
  GITHUB_ACTIONS = "github-actions",
  MATERIAL_UI = "material-ui",
  ANT_DESIGN = "ant-design",
  WEBPACK = "webpack",
  BABEL = "babel",
  ESLINT = "eslint",
  PRETTIER = "prettier",
  STORYBOOK = "storybook",
  PLAYWRIGHT = "playwright",
  FRAMER = "framer",
  CANVAS = "canvas",
  SHADCN = "shadcn",
  GOOGLE_ANALYTICS = "google-analytics",
  GOOGLE_SEARCH_CONSOLE = "google-search-console",
  STYLED_COMPONENTS = "styled-components",
  VERCEL = "vercel",
  NETLIFY = "netlify",
  HEROKU = "heroku",
  REDIS = "redis",
  SOCKET_IO = "socket-io",
  REACT_QUERY = "react-query",
  MARKDOWN = "markdown",
  PM2 = "pm2",
  POSTMAN = "postman",
  SWAGGER = "swagger",
  GOOGLE_MAPS = "google-maps",
  GOOGLE_PLAY = "google-play",
  APPLE_APP_STORE = "apple-app-store",
  VUE = "vue",
  REACT_ROUTER = "react-router",
  ANDROID_STUDIO = "android-studio",
  XCODE = "xcode",
  EXPO = "expo",
  VITE = "vite",
  JWT = "jwt",
  AUTH0 = "auth0",
  FIREBASE = "firebase",
  FASTLANE = "fastlane",
  MYSQL = "mysql",
  LINUX = "linux",
}
